package gastmappers.rpgmapper.mapperutilities.Statements.Specification.CTypeStatements.Opcodes;

/**
 * Lista con los enum con los opcode.
 *
 * @author Equipo de trabajo AVIB
 * @version 1.0
 * @since 1.0
 */
public enum OpcodeEnum {
	ACQ, ADD, ADDDUR, ALLOC, AND, BEGSR, BITON, BITOFF, CAB, CALL, CALLB, CALLP, CAS, CAT, CHAIN, CHECK, CHECKR, CLEAR,
	CLOSE, COMMIT, COMP, DEALLOC, DEFINE, DELETE, DIV, DO, DOU, DOW, DSPLY, DUMP, ELSE, END, EVAL, EVALR, EXCEPT, EXFMT,
	EXSR, EXTRCT, FEOD, FOR, FORCE, GOTO, IF, IN, ITER, KFLD, KLIST, LEAVE, LEAVESR, LOOKUP, MHHZO, MHLZO, MLHZO, MLLZO,
	MONITOR, MOVEA, MOVE, MOVEL, MULT, MVR, NEXT, OCCUR, ONERROR, OPEN, OR, OUT, OTHER, PARM, PLIST, POST, READ, READC,
	READE, READP, READPE, REALLOC, REL, RESET, RETURN, ROLBK, SCAN, SELECT, SETGT, SETLL, SETOFF, SETON, SHTDN, SORTA,
	SQRT, SUB, SUBDUR, SUBST, TAG, TEST, TESTB, TESTN, TESTZ, TIME, UNLOCK, UPDATE, WHEN, WRITE, XFOOT, XLATE, ZADD,
	ZSUB, FREECONTEXT
}
